# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: julia-formatter
        name: Julia Formatter
        entry: julia scripts/format-check.jl
        language: system
        files: \.jl$
        pass_filenames: true
        description: "Format Julia files only if formatting changes are needed"
      
