name = "Kaimon"
uuid = "d3856c55-31fd-4246-b7e8-380411123c01"
version = "1.0.0"
authors = ["Kahli Burke <kahli@kahliburke.com>"]

[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
OteraEngine = "b2d7f28f-acd6-4007-8b26-bc27716e5513"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Supposition = "5a0628fe-1738-4658-9b6d-0b7605a9755b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tachikoma = "468859d6-42d8-48b7-8ad9-1d312e0e3b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
Aqua = "0.8"
CommonMark = "0.8.16"
Coverage = "1.8.1"
DBInterface = "2.6.1"
DataFrames = "1.8.1"
Dates = "1.10"
FreeTypeAbstraction = "0.10.8"
HTTP = "1.10"
InteractiveUtils = "1.10"
JSON = "1"
JuliaFormatter = "1, 2"
Logging = "1.11.0"
LoggingExtras = "1.2.0"
Match = "2.4.1"
OteraEngine = "1.1.3"
PNGFiles = "0.4.4"
Pkg = "1.10"
Preferences = "1"
Printf = "1.10"
Profile = "1.10"
REPL = "1.10"
Random = "1.10"
ReTest = "0.3.4"
SHA = "0.7, 1"
SQLite = "1.6.1"
Serialization = "1.11.0"
Sockets = "1.11.0"
Supposition = "0.3.5"
TOML = "1.0"
Tachikoma = "1.0.0"
Test = "1.10"
UUIDs = "1.11.0"
ZMQ = "1"
julia = "1.12"

[sources]
Tachikoma = {url = "https://github.com/kahliburke/Tachikoma.jl"}

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Dates", "Aqua", "JuliaFormatter", "JET"]
